const baseTextProperties = {
  fill: "#111",
  fontFamily: "Arial",
  fontWeight: "400",
  fontSize: "20",
  borderColor: "#f00",
  editingBorderColor: "#0f0",
  cornerStrokeColor: "#f00",
  cornerStyle: "circle",
};

export default [
  {
    name: "Kapak",
    backgroundUrl: "img/cover.png",
    width: 640,
    height: 786,
    textFields: [
      {
        ...baseTextProperties,
        text: "QUICK FOX JUMPED!!!",
        width: 500,
        left: 120,
        top: 260,
        fontSize: 36,
        fontWeight: 400,
      },
      {
        ...baseTextProperties,
        text: "Quick Fox Jumped Over",
        width: 500,
        left: 120,
        top: 320,
        fontSize: 32,
        fontWeight: 900,
      },
      {
        ...baseTextProperties,
        text: "Quick Fox Jumped Over The",
        width: 500,
        left: 120,
        top: 380,
        fontSize: 30,
        fontWeight: 600,
      },
      {
        ...baseTextProperties,
        text: "Quick Fox Jumped Over The",
        width: 500,
        left: 120,
        top: 440,
        fontSize: 27,
        fontWeight: 600,
      },
    ],
  },
  {
    name: "Sayfa 1",
    backgroundUrl: "./img/default.png",
    width: 640,
    height: 786,
    textFields: [
      {
        ...baseTextProperties,
        fontWeight: 700,
        width: 200,
        text: "u/kullanici_adi_1",
        left: 60,
        top: 180,
      },
      {
        ...baseTextProperties,
        fontWeight: 700,
        width: 200,
        text: "u/kullanici_adi_2",
        left: 60,
        top: 360,
      },
      {
        ...baseTextProperties,
        fontWeight: 700,
        width: 200,
        text: "u/kullanici_adi_3",
        left: 60,
        top: 560,
      },
      {
        ...baseTextProperties,
        fontWeight: 600,
        width: 390,
        text: `Baslik_1`,
        left: 230,
        top: 140,
      },
      {
        ...baseTextProperties,
        fontWeight: 600,
        width: 390,
        text: `Baslik_2`,
        left: 230,
        top: 320,
      },
      {
        ...baseTextProperties,
        fontWeight: 600,
        width: 390,
        text: `Baslik_3`,
        left: 230,
        top: 520,
      },
      {
        ...baseTextProperties,
        width: 390,
        text: `Haber_metni_1`,
        left: 230,
        top: 180,
      },
      {
        ...baseTextProperties,
        width: 390,
        text: `Haber_metni_2`,
        left: 230,
        top: 360,
      },
      {
        ...baseTextProperties,
        width: 390,
        text: `Haber_metni_3`,
        left: 230,
        top: 560,
      },
    ],
  },
  {
    name: "Son Sayfa",
    backgroundUrl: "img/last.jpg",
    width: 640,
    height: 786,
    textFields: [],
  },
  {
    name: "Iki Haberli Sayfa",
    backgroundUrl: "./img/default.png",
    width: 640,
    height: 786,
    textFields: [
      {
        ...baseTextProperties,
        fontWeight: 600,
        width: 200,
        text: "u/kullanici_adi_1",
        left: 60,
        top: 200,
      },
      {
        ...baseTextProperties,
        fontWeight: 600,
        width: 200,
        text: "u/kullanici_adi_2",
        left: 60,
        top: 460,
      },
      {
        ...baseTextProperties,
        fontWeight: 700,
        width: 390,
        text: `Baslik_1`,
        left: 230,
        top: 160,
      },
      {
        ...baseTextProperties,
        fontWeight: 700,
        width: 390,
        text: `Baslik_2`,
        left: 230,
        top: 420,
      },
      {
        ...baseTextProperties,
        width: 390,
        text: `Haber_metni_1`,
        left: 230,
        top: 200,
      },
      {
        ...baseTextProperties,
        width: 390,
        text: `Haber_metni_2`,
        left: 230,
        top: 460,
      },
    ],
  },
  {
    name: "Iki Haberli Sayfa",
    backgroundUrl: "./img/default.png",
    width: 640,
    height: 786,
    textFields: [
      {
        ...baseTextProperties,
        fontWeight: 600,
        width: 200,
        text: "u/kullanici_adi_1",
        left: 230,
        top: 200,
      },

      {
        ...baseTextProperties,
        fontWeight: 700,
        width: 390,
        text: `Baslik_1`,
        left: 230,
        top: 150,
      },
      {
        ...baseTextProperties,
        width: 560,
        text: `Haber_metni_1`,
        left: 60,
        top: 250,
      },
    ],
  },
];
